ublue-os/aurora-docs

docusaurus.config.ts
sidebars.ts

This adds algolia search functionality to the docs site.

add search functionality

---

docusaurus.config.ts
sidebars.ts

Reverts NiHaiden/aurora-docs#15

Revert "add search functionality"

---

docs/guides/secondary-drives.md

@nicknamenamenick 
if you have the guide added please run "npm run prettier"
this will format the code and markdown files, otherwise prettier will complain and we won't get a new deployment 😅

format guide

---

.github/workflows/prettier.yml

This PR adds formatting with prettier during a PR and on a push on main.

add prettier formatting

---

docs/reference/example.md

add some text for the upstream documentation to make it less empty

add some text for the upstream documentation to make it less empty

---

docs/guides/alternate-install-guide.md
docs/guides/installation-troubleshoot.md
sidebars.ts

Draft PR for now. Adds some installation guides.

Add some installation guides

---

docs/guides/intro.md

pretty sure we don't ship kalendar so i just replaced it with konsole

fix spelling and add konsole

---

docs/guides/report-issues.md
sidebars.ts

Adds a short and sweet guide on reporting issues.  Feel free to add suggestions and edits! :)

feat: Add 'report issues' guide

---

docs/guides/install-guide.md
sidebars.ts

It's really simple, simpler than the surface installation guide even, but I figure for now it's something.  This is the last new documentation that I plan to add today.  As always, feel free to do whatever you want with this, aurora maintainers.

feat: Add a really quick and dirty general installation guide

---

docs/dx/aurora-dx-intro.md

Fix reference to ujust recipe: dx-group

---

.github/workflows/pdf.yml

feat: generate docs as pdf

---

docs/guides/gaming.md

Adds mention about the nvidia-open image

feat: update gaming section with nvidia-open driver mention

---

docs/guides/credits.md

Add Chandeleer to the credits page

docs: add chandeleer with a special shoutout

---

docs/guides/intro.md

mention ktailctl add distroshelf

feat: add homepage URL for installed apps

---

docker-compose.yml

Reverts ublue-os/aurora-docs#110

Revert "chore(deps): update node.js to 601f205"

---

docker-compose.yml

Reverts ublue-os/aurora-docs#109

Revert "chore(deps): update node.js to 0d6c471"

---

docs/guides/gaming.md

hwe will be dead, there are no "specialized" ISOs anymore

chore: remove outdated surface and asus mention

---

docs/guides/disable-airplay-discovery.md
sidebars.ts

Create a guide which shows the user on how to disable auto airplay discovery.

feat: add guide for disabling airplay autodiscovery

---

docs/guides/release-streams.md
sidebars.ts

Adds a documentation for different release streams Aurora provides
Closes https://github.com/ublue-os/aurora-docs/issues/93

feat: Document the different release streams

---

docs/guides/release-streams.md

Updated the Gated Kernel section header to improve formatting and clarity.

fix: Fix header formatting for Gated Kernel section

---

package-lock.json
package.json

Reverts ublue-os/aurora-docs#185

Revert "fix(deps): update docusaurus monorepo to v3.8.1"

---

docs/guides/software.md

closes https://github.com/ublue-os/aurora-docs/issues/116

feat: add docker instructions
